Repository WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam, pull requests merged in 2024-10, with the labels that each got.

#54 :sparkles: Us 39 admin front to back and admin delete recipes
  client/src/components/navbar/Navbar.jsx
  client/src/main.jsx
  client/src/pages/leBuffet/Buffet.jsx
  client/src/pages/leBuffet/DishCard.jsx
  client/src/pages/userAdmin/PanelAdminRecipes.jsx
  client/src/services/loader/adminRecipesLoader.js
  client/src/services/loader/buffetLoader.js
  server/app/controllers/recipeActions.js
  server/app/services/auth.js
  server/database/schema.sql
  server/public/upload/dessert1.jpg
  server/public/upload/dessert2.jpg
  server/public/upload/dessert3.jpg
  server/public/upload/entree1.jpg
  server/public/upload/entree2.jpg
  server/public/upload/entree3.jpg
  server/public/upload/omelette.jpg
  server/public/upload/plat1.jpg
  server/public/upload/plat2.jpg
  server/public/upload/plat3.jpg
  server/public/upload/salad-caesar.jpg
  server/public/upload/soufflés-au-fromage.jpg
Labels: REVIEWED

#64 :hammer: add features for admin comments. Wait join with backend
  client/src/main.jsx
  client/src/pages/userAdmin/PanelAdminComments.jsx
  client/src/styles/panelAdmin/AdminComments.css
Labels: REVIEWED

#65 ✨ Add client side favorite
  client/src/pages/RecipesInstruction.jsx
  client/src/services/fetchFavorite.js
  server/app/controllers/favoriteActions.js
  server/app/router/favoriteRouter.js
Labels: REVIEWED

#66 :hammer: Us 22 recette sql
  client/src/pages/RecipesInstruction.jsx
  server/app/router/difficultyRouter.js
  server/database/schema.sql
Labels: REVIEWED

#67 :bento: :see_no_evil: Us 22 image recipe
  server/database/schema.sql
  server/public/upload/omelette.jpg
  server/public/upload/salad-caesar.jpg
  server/public/upload/soufflés-au-fromage.jpg
Labels: REVIEWED

#69 Us 39 panel admin comments
  client/src/components/Comment.jsx
  client/src/main.jsx
  client/src/pages/RecipesInstruction.jsx
  client/src/pages/userAdmin/PanelAdmin.jsx
  client/src/pages/userAdmin/PanelAdminComments.jsx
  client/src/services/loader/adminCommentsLoader.js
  client/src/styles/panelAdmin/AdminComments.css
  server/app/controllers/commentActions.js
  server/database/models/CommentRepository.js
Labels: REVIEWED

#72 ✨ Display favorite in user page
  client/src/main.jsx
  client/src/pages/User.jsx
  client/src/pages/user/Recipe.jsx
  client/src/pages/user/RecipeSection.jsx
  client/src/services/fetchFavorite.js
  client/src/services/fetchRecipe.js
  client/src/services/loader/userLoader.js
  server/app/controllers/recipeActions.js
  server/database/models/FavoriteRepository.js
  server/database/models/RecipeRepository.js
Labels: REVIEWED

#74 :lipstick: add CSS and div on jsx
  client/src/components/Comment.jsx
  client/src/styles/recipesinstruction.css
Labels: REVIEWED

#73 :lipstick: Us 00 fix css
  client/src/assets/images/user_pictures.svg
  client/src/pages/TheRecipes.jsx
  client/src/pages/User.jsx
  client/src/styles/Auth.css
  client/src/styles/carrousel.css
  client/src/styles/home/recipeCard.css
  client/src/styles/recipesinstruction.css
  client/src/styles/user.css
  server/database/schema.sql
Labels: REVIEWED

#71 :hammer: finish feature buffet
  client/src/main.jsx
  client/src/pages/BuffetSelect.jsx
  client/src/pages/leBuffet/Buffet.jsx
  client/src/pages/leBuffet/DishCard.jsx
  client/src/services/fetchFavorite.js
  client/src/styles/buffetSelect.css
  client/src/styles/leBuffet/Buffet.css
  client/src/styles/leBuffet/DishCard.css
Labels: CONFLICTS RESOLVED, REVIEWED

#75 :bug: Fix bugs
  client/src/components/Carrousel.jsx
  client/src/pages/RecipesInstruction.jsx
  client/src/pages/TheRecipes.jsx
  client/src/pages/User.jsx
  client/src/pages/createRecipe/Header.jsx
  client/src/pages/home/RecipeCard.jsx
  client/src/pages/home/SeeMoreRecipe.jsx
  client/src/pages/userAdmin/PanelAdminRecipes.jsx
  client/src/styles/carrousel.css
  client/src/styles/panelAdmin/AdminRecipes.css
  client/src/styles/recipesinstruction.css
  client/src/styles/therecipes.css
  client/src/styles/user.css
  client/src/styles/userProfile/userInfo.css
  server/database/schema.sql
Labels: REVIEW REQUESTED
