Repository WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-eating-nam-nam, pull requests merged in 2024-09, with the labels that each got.

#4 🔨 Modified Us 36 ingredient management
  server/app/controllers/ingredientActions.js
  server/app/router/ingredientsRouter.js
  server/database/models/IngredientRepository.js
  server/database/models/ItemRepository.js
  server/database/schema.sql
Labels: REVIEW REQUESTED, REVIEWED

#5 :hammer: add bread User
  server/app/controllers/userActions.js
  server/app/router.js
  server/app/router/userRouter.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEW REQUESTED, REVIEWED

#6 :hammer: Us 01 add recipe
  server/app/controllers/recipeActions.js
  server/app/router.js
  server/app/router/recipesRouter.js
  server/database/models/RecipeRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEW REQUESTED, REVIEWED

#7 :hammer: CRUD difficulty done
  server/app/controllers/difficultyActions.js
  server/app/router.js
  server/app/router/difficultyRouter.js
  server/database/models/DifficultyRepository.js
Labels: CORRECTIONS DONE, REVIEWED

#8 🔨 Add Navbar
  client/src/App.jsx
  client/src/assets/.gitkeep
  client/src/assets/images/logo.svg
  client/src/components/.gitkeep
  client/src/components/Navbar.jsx
  client/src/main.jsx
  client/src/pages/.gitkeep
  client/src/pages/Home.jsx
  client/src/styles/App.css
  client/src/styles/Navbar.css
  client/src/styles/main.css
Labels: CORRECTIONS DONE

#9 :coffin: remove comments and clean server
  server/app/controllers/difficultyActions.js
  server/app/controllers/ingredientActions.js
  server/app/controllers/itemActions.js
  server/app/controllers/recipeActions.js
  server/app/controllers/userActions.js
  server/app/router.js
  server/app/router/difficultyRouter.js
  server/app/router/ingredientsRouter.js
  server/app/router/itemsRouter.js
  server/database/models/DifficultyRepository.js
  server/database/models/IngredientRepository.js
  server/database/models/ItemRepository.js
  server/database/models/RecipeRepository.js
  server/database/models/UserRepository.js
  server/database/schema.sql
Labels: REVIEW REQUESTED

#11 📱 Add responsive to Navbar
  client/src/App.jsx
  client/src/assets/images/close.svg
  client/src/assets/images/logo.svg
  client/src/assets/images/menu.svg
  client/src/components/navbar/MenuBurger.jsx
  client/src/components/navbar/Navbar.jsx
  client/src/styles/Navbar.css
  client/src/styles/main.css
  client/src/styles/navbar.css
Labels: REVIEWED

#12 :sparkles: Us 14 authentification
  package-lock.json
  server/app/config.js
  server/app/controllers/authActions.js
  server/app/router.js
  server/app/router/authRouter.js
  server/app/router/userRouter.js
  server/app/services/auth.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/package.json
Labels: REVIEWED

#13 :twisted_rightwards_arrows: Complete home page
  client/src/assets/images/loupe.png
  client/src/assets/images/oeuf.png
  client/src/pages/Home.jsx
  client/src/pages/home/Advice.jsx
  client/src/pages/home/Advices.jsx
  client/src/pages/home/Buffet.jsx
  client/src/pages/home/Reception.jsx
  client/src/pages/home/RecipeCard.jsx
  client/src/pages/home/SeeMoreRecipe.jsx
  client/src/styles/home.css
  client/src/styles/home/advice.css
  client/src/styles/home/buffet.css
  client/src/styles/home/reception.css
  client/src/styles/home/recipeCard.css
  client/src/styles/home/seeMoreRecipe.css
  client/src/styles/main.css
Labels: REVIEWED

#16 :sparkles: Create register
  client/src/main.jsx
  client/src/pages/Login.jsx
  client/src/pages/SignUp.jsx
  client/src/styles/Auth.css
  client/src/styles/main.css
  server/app/config.js
  server/app/controllers/authActions.js
  server/app/controllers/userActions.js
  server/app/router/authRouter.js
  server/app/router/recipesRouter.js
  server/app/services/auth.js
  server/app/services/middleware.js
  server/database/models/UserRepository.js
Labels: REVIEWED

#18 💄 Add "CreateRecipe" route
  client/package.json
  client/src/assets/images/photo.svg
  client/src/main.jsx
  client/src/pages/CreateRecipe.jsx
  client/src/pages/createRecipe/Header.jsx
  client/src/pages/createRecipe/Step.jsx
  client/src/styles/create/create.css
  client/src/styles/create/header.css
  client/src/styles/create/recipeSteps.css
  client/src/styles/main.css
  client/src/styles/navbar.css
Labels: REVIEWED

#17 :sparkles: Us13 carrousel
  client/src/assets/images/banane_caramelisee.svg
  client/src/assets/images/barre_glace_chocolat.svg
  client/src/assets/images/bruschetta.svg
  client/src/assets/images/carpaccio_de_boeuf.svg
  client/src/assets/images/cheeseburger.svg
  client/src/assets/images/compote_de_pomme.svg
  client/src/assets/images/crepe_abricot.svg
  client/src/assets/images/foie_gras.svg
  client/src/assets/images/fraises_chantilly.svg
  client/src/assets/images/galette_complete.svg
  client/src/assets/images/gaufre_sauce_chocolat.svg
  client/src/assets/images/gazpacho_tomate.svg
  client/src/assets/images/makis.svg
  client/src/assets/images/nougat.svg
  client/src/assets/images/pancakes_sirop_erable.svg
  client/src/assets/images/pate_bolognaise.svg
  client/src/assets/images/poisson_haricots_puree.svg
  client/src/assets/images/porc_au_caramel.svg
  client/src/assets/images/poulet_au_curry.svg
  client/src/assets/images/poulet_aux_olives.svg
  client/src/assets/images/puree_steak.svg
  client/src/assets/images/salade_de_fruits.svg
  client/src/assets/images/salade_de_pate.svg
  client/src/assets/images/salade_lyonnaise.svg
  client/src/assets/images/soupe_potimarron.svg
  client/src/components/navbar/Carrousel.jsx
  client/src/main.jsx
  client/src/pages/TheRecipes.jsx
  client/src/styles/carrousel.css
  client/src/styles/therecipes.css
  package-lock.json
  server/public/assets/images/banane_caramelisee.svg
  server/public/assets/images/barre_glace_chocolat.svg
  server/public/assets/images/bruschetta.svg
  server/public/assets/images/carpaccio_de_boeuf.svg
  server/public/assets/images/cheeseburger.svg
  server/public/assets/images/close.svg
  server/public/assets/images/compote_de_pomme.svg
  server/public/assets/images/crepe_abricot.svg
  server/public/assets/images/foie_gras.svg
  server/public/assets/images/fraises_chantilly.svg
  server/public/assets/images/galette_complete.svg
  server/public/assets/images/gaufre_sauce_chocolat.svg
  server/public/assets/images/gazpacho_tomate.svg
  server/public/assets/images/makis.svg
  server/public/assets/images/nougat.svg
  server/public/assets/images/omelette_garnies.svg
  server/public/assets/images/pancakes_sirop_erable.svg
  server/public/assets/images/pate_bolognaise.svg
  server/public/assets/images/poisson_haricots_puree.svg
  server/public/assets/images/porc_au_caramel.svg
  server/public/assets/images/poulet_au_curry.svg
  server/public/assets/images/poulet_aux_olives.svg
  server/public/assets/images/puree_steak.svg
  server/public/assets/images/salade_de_fruits.svg
  server/public/assets/images/salade_de_pate.svg
  server/public/assets/images/salade_lyonnaise.svg
  server/public/assets/images/soupe_potimarron.svg
  server/public/assets/images/spaghettis_bolognaise.svg
Labels: REVIEWED

#20 💄 Fix issues with ui
  client/src/main.jsx
  client/src/styles/Auth.css
Labels: REVIEW REQUESTED

#21 🩹 Fix global style
  client/src/styles/home/reception.css
Labels: REVIEWED

#22 :wrench: Axios Request in SignUp and Login
  client/src/main.jsx
  client/src/pages/Login.jsx
  client/src/pages/SignUp.jsx
Labels: REVIEWED

#23 :adhesive_bandage: Fix link to english
  client/src/components/navbar/Navbar.jsx
Labels: REVIEWED

#24 Panel-Admin finish
  client/src/main.jsx
  client/src/pages/CreateRecipe.jsx
  client/src/pages/createRecipe/Header.jsx
  client/src/pages/createRecipe/Step.jsx
  client/src/pages/userAdmin/PanelAdmin.jsx
  client/src/styles/panelAdmin/dashboard.css
  package-lock.json
Labels: CHANGES REQUESTED, CORRECTIONS DONE

#25 🐛 Fix auth form login and signup
  client/src/pages/Login.jsx
  client/src/pages/SignUp.jsx
  client/src/styles/Auth.css
  server/app/controllers/authActions.js
  server/database/models/UserRepository.js
  server/database/schema.sql
Labels: CORRECTIONS DONE

#26 🚧 UserInfo page in development
  client/src/assets/images/user_picture.png
  client/src/main.jsx
  client/src/pages/UserProfile.jsx
  client/src/pages/userProfile/PersonalInfo.jsx
  client/src/pages/userProfile/UserInfo.jsx
  client/src/styles/home/reception.css
  client/src/styles/userProfile/personalInfo.css
  client/src/styles/userProfile/userInfo.css
Labels: REVIEWED

#27 :adhesive_bandage: Fix login credential
  client/src/pages/Login.jsx
Labels: REVIEWED

#28 🗃️ Change database from 'pseudo' to 'fullname' for greater sign-up clarity
  client/src/pages/SignUp.jsx
  server/app/controllers/authActions.js
  server/database/models/UserRepository.js
  server/database/schema.sql
Labels: REVIEWED

#30 :twisted_rightwards_arrows: Merge UserProfile
  client/src/pages/UserProfile.jsx
  client/src/pages/userProfile/PersonalInfo.jsx
  client/src/pages/userProfile/UserInfo.jsx
  client/src/services/request.js
  client/src/services/requestUserProfile.js
  client/src/styles/userProfile/personalInfo.css
  client/src/styles/userProfile/userInfo.css
  server/app/controllers/userActions.js
  server/app/router/userRouter.js
  server/app/services/auth.js
  server/database/models/UserRepository.js
Labels: CONFLICTS RESOLVED, REVIEWED

#31 Us 21 le buffet
  client/src/assets/images/Dessert-buffet.png
  client/src/assets/images/Entrée-buffet.png
  client/src/assets/images/Plat-buffet.png
  client/src/assets/images/buffet-quote.png
  client/src/assets/images/dessert1.jpg
  client/src/assets/images/dessert2.jpg
  client/src/assets/images/dessert3.jpg
  client/src/assets/images/entree1.jpg
  client/src/assets/images/entree2.jpg
  client/src/assets/images/entree3.jpg
  client/src/assets/images/plat1.jpg
  client/src/assets/images/plat2.jpg
  client/src/assets/images/plat3.jpg
  client/src/main.jsx
  client/src/pages/leBuffet/Buffet.jsx
  client/src/pages/leBuffet/DishCard.jsx
  client/src/styles/leBuffet/Buffet.css
  client/src/styles/leBuffet/DishCard.css
Labels: CONFLICTS RESOLVED, CORRECTIONS DONE

#32 :sparkles: Us 25 consult recipe
  client/src/components/Carrousel.jsx
  client/src/pages/RecipesInstruction.jsx
  client/src/pages/TheRecipes.jsx
  server/app/controllers/uploadActions.js
  server/app/router/uploadRouter.js
  server/database/models/RecipeRepository.js
  server/database/schema copy.sql
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEWED

#33 💄 Update CSS and classname
  client/src/pages/userProfile/PersonalInfo.jsx
  client/src/pages/userProfile/UserInfo.jsx
  client/src/styles/userProfile/personalInfo.css
  client/src/styles/userProfile/userInfo.css
Labels: REVIEWED

#35 🩹 Fix css for the navbar
  client/src/styles/navbar.css
Labels: REVIEWED

#37 :lipstick: modif CSS for fix a detail
  client/src/styles/leBuffet/Buffet.css
Labels: REVIEWED

#36 :hammer: Add upload to the backend
  package-lock.json
  server/app/config.js
  server/app/router.js
  server/app/router/uploadRouter.js
  server/package.json
Labels: CORRECTIONS DONE, REVIEWED

#38 ✨ Add create recipe page
  client/src/main.jsx
  client/src/pages/CreateRecipe.jsx
  client/src/pages/createRecipe/Header.jsx
  client/src/pages/createRecipe/Ingredients.jsx
  client/src/pages/createRecipe/Step.jsx
  client/src/services/fetchDifficulties.js
  client/src/services/loader/createRecipeLoader.js
  client/src/styles/create/ingredients.css
  client/src/styles/home/reception.css
  package-lock.json
  server/app/controllers/recipeActions.js
  server/app/services/auth.js
  server/database/models/RecipeRepository.js
  server/database/models/RecipeStepRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: CORRECTIONS DONE, REVIEWED

#40 🩹 Fix schema.sql
  server/database/schema.sql
Labels: REVIEWED

#41 :sparkles: Us 22 recette sql
  client/src/pages/RecipesInstruction.jsx
  client/src/styles/recipesinstruction.css
  server/database/schema.sql
  server/public/upload/Boeuf-bourguignon.jpg
  server/public/upload/canard-orange.jpg
  server/public/upload/crepes.jpg
  server/public/upload/curry de légumes.jpg
  server/public/upload/foie-gras.jpg
  server/public/upload/lasagne-bolognaise.jpg
  server/public/upload/omelette.jpg
  server/public/upload/pates-carbonara.jpg
  server/public/upload/poulet-curry.jpg
  server/public/upload/quiche-thon-tomates.jpg
  server/public/upload/ratatouille.jpg
  server/public/upload/salad-caesar.jpg
  server/public/upload/soufflés-au-fromage.jpg
  server/public/upload/tarte-au-citron-meringuée.jpg
  server/public/upload/tarte-tatin.jpg
Labels: REVIEWED

#39 :sparkles:Us 25 consult recipe
  client/src/components/Carrousel.jsx
  client/src/main.jsx
  client/src/pages/RecipesInstruction.jsx
  client/src/pages/TheRecipes.jsx
  client/src/pages/createRecipe/Step.jsx
  client/src/services/loader/recipeLoader.js
  client/src/styles/carrousel.css
  server/app/controllers/authActions.js
  server/app/controllers/difficultyActions.js
  server/app/controllers/ingredientActions.js
  server/app/controllers/recipeActions.js
  server/app/controllers/userActions.js
  server/app/router/authRouter.js
  server/app/router/difficultyRouter.js
  server/app/router/ingredientsRouter.js
  server/app/router/itemsRouter.js
  server/app/router/uploadRouter.js
  server/app/router/userRouter.js
  server/app/services/auth.js
  server/database/models/DifficultyRepository.js
  server/database/models/IngredientRepository.js
  server/database/models/RecipeStepRepository.js
  server/database/models/UserRepository.js
  server/database/schema.sql
Labels: CORRECTIONS DONE

#43 Us 28 users comments
  client/src/main.jsx
  client/src/pages/RecipesInstruction.jsx
  client/src/pages/userAdmin/PanelAdminRecipes.jsx
  client/src/styles/navbar.css
  client/src/styles/panelAdmin/AdminRecipes.css
  client/src/styles/recipesinstruction.css
  server/app/controllers/commentActions.js
  server/app/router.js
  server/app/router/commentRouter.js
  server/database/models/CommentRepository.js
  server/database/models/RecipeRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: CORRECTIONS DONE, REVIEWED

#44 :zap: Us 12 home page
  client/src/pages/Home.jsx
  client/src/pages/home/RecipeCard.jsx
  client/src/pages/home/SeeMoreRecipe.jsx
  server/app/controllers/recipeActions.js
  server/app/router/recipesRouter.js
  server/database/models/RecipeRepository.js
Labels: REVIEWED

#46 :sparkles: Us 35 delete recipes
  client/src/pages/RecipesInstruction.jsx
  client/src/services/handleDeleteRecipe.js
  client/src/styles/recipesinstruction.css
  server/app/controllers/authActions.js
  server/app/controllers/recipeActions.js
  server/app/router/recipesRouter.js
  server/app/router/userRouter.js
  server/app/services/auth.js
  server/database/models/RecipeRepository.js
  server/database/schema.sql
Labels: REVIEWED

#48 ✨ Add Auth logic
  client/src/components/ProtectedRoute.jsx
  client/src/components/navbar/Navbar.jsx
  client/src/context/authContext.jsx
  client/src/main.jsx
  client/src/pages/Login.jsx
  client/src/services/auth.js
  client/src/styles/navbar.css
  server/app/controllers/authActions.js
  server/app/router/authRouter.js
  server/app/services/auth.js
Labels: REVIEWED

#49 ✨ Searchbar Finished
  client/src/pages/home/Reception.jsx
  client/src/styles/home/reception.css
Labels: REVIEWED

#47 :sparkles: Added a method to submit comments on the front end to dis…
  client/src/pages/RecipesInstruction.jsx
  client/src/styles/recipesinstruction.css
  server/database/models/CommentRepository.js
Labels: REVIEWED

#50 ✨ Add upload to recipe
  client/src/pages/CreateRecipe.jsx
  client/src/pages/createRecipe/Header.jsx
  client/src/styles/create/header.css
  server/.gitignore
  server/app/config.js
  server/app/controllers/recipeActions.js
  server/app/router/recipesRouter.js
  server/database/models/RecipeRepository.js
  server/database/schema.sql
Labels: REVIEWED

#52 :adhesive_bandage: fix bug comment, problem resolve, comment is fonc…
  client/src/pages/RecipesInstruction.jsx
  client/src/services/loader/recipeLoader.js
  server/app/controllers/commentActions.js
  server/app/router/commentRouter.js
  server/app/services/auth.js
  server/database/models/CommentRepository.js
  server/database/models/RecipeRepository.js
  server/database/schema.sql
Labels: REVIEWED

#51 :recycle: Us 13 categorie recipes
  client/src/components/Carrousel.jsx
  client/src/main.jsx
  client/src/pages/TheRecipes.jsx
  client/src/services/loader/categoryLoader.js
  server/app/controllers/categoryActions.js
  server/app/controllers/recipeActions.js
  server/app/router.js
  server/app/router/categoryRouter.js
  server/database/models/CategoryRepository.js
  server/database/models/RecipeRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEWED

#53 Us 28 users comments
  client/src/components/Comment.jsx
  client/src/pages/RecipesInstruction.jsx
  server/app/controllers/authActions.js
  server/app/controllers/commentActions.js
  server/app/router/commentRouter.js
  server/app/services/auth.js
  server/database/models/CommentRepository.js
  server/database/schema.sql
Labels: REVIEWED

#55 :hammer: :lipstick: Us 22 recette sql
  client/src/components/Carrousel.jsx
  client/src/pages/RecipesInstruction.jsx
  client/src/pages/home/RecipeCard.jsx
  client/src/pages/home/SeeMoreRecipe.jsx
  client/src/services/loader/categoryLoader.js
  client/src/styles/carrousel.css
  client/src/styles/home/recipeCard.css
  client/src/styles/home/seeMoreRecipe.css
  client/src/styles/recipesinstruction.css
  server/database/models/CategoryRepository.js
  server/database/models/RecipeRepository.js
  server/database/schema.sql
  server/public/upload/curry de légumes.jpg
Labels: REVIEWED

#56 🚚 add last link
  client/src/components/navbar/MenuBurger.jsx
  client/src/components/navbar/Navbar.jsx
  client/src/pages/User.jsx
  client/src/pages/home/Buffet.jsx
  client/src/pages/home/RecipeCard.jsx
  client/src/pages/home/SeeMoreRecipe.jsx
Labels: REVIEWED

#57 :lipstick: :bento: Us 22 recette sql
  client/index.html
  client/src/assets/images/banane_caramelisee.svg
  client/src/assets/images/barre_glace_chocolat.svg
  client/src/styles/home/recipeCard.css
  client/src/styles/home/seeMoreRecipe.css
  server/database/schema.sql
Labels: REVIEWED

#58 🩹 Minor fix on recipes, homepage, and create-recipe page
  client/src/components/navbar/Navbar.jsx
  client/src/pages/CreateRecipe.jsx
  client/src/pages/RecipesInstruction.jsx
  client/src/pages/TheRecipes.jsx
  client/src/pages/createRecipe/Header.jsx
  client/src/pages/createRecipe/Step.jsx
  client/src/services/loader/createRecipeLoader.js
  client/src/styles/create/header.css
  client/src/styles/panelAdmin/AdminRecipes.css
  client/src/utils/capitalize.js
  server/app/controllers/recipeActions.js
  server/app/router/recipesRouter.js
  server/database/models/RecipeRepository.js
Labels: REVIEWED

#59 Us 0 fix css
  client/src/components/Comment.jsx
  client/src/services/loader/categoryLoader.js
  client/src/services/requestSearchbar.js
  client/src/styles/Auth.css
  client/src/styles/carrousel.css
  client/src/styles/footer.css
  client/src/styles/home/buffet.css
  client/src/styles/main.css
  client/src/styles/navbar.css
  client/src/styles/recipesinstruction.css
Labels: REVIEWED

#62 :hammer: add button panel-admin on user page and add last link
  client/src/pages/User.jsx
  client/src/pages/userAdmin/PanelAdmin.jsx
  client/src/styles/panelAdmin/dashboard.css
  client/src/styles/user.css
  server/app/controllers/authActions.js
  server/app/services/auth.js
Labels: REVIEWED

#60 ✨ Add server side favorite
  server/app/controllers/favoriteActions.js
  server/app/router.js
  server/app/router/favoriteRouter.js
  server/database/models/FavoriteRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEWED

#63 🔨 add upload images for searchbar and link
  client/src/pages/home/Reception.jsx
  client/src/styles/home/reception.css
  server/database/models/RecipeRepository.js
Labels: REVIEWED
